# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 'build-azure'
#- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: "Building Web App"
  jobs:
  - job: Building job
    displayName: "This is the building job"
    steps:
    - script: echo Beginning build
      displayName: 'Running build job'
    - task: DotNetCoreCLI@2
      inputs: 
        command: 'build'